"""Add role_id column to users table and create rbac tables

Revision ID: 14a2a1adcf48
Revises: 5193c3d44251
Create Date: 2025-10-26 10:22:52.325804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a2a1adcf48'
down_revision: Union[str, Sequence[str], None] = '5193c3d44251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
